# Generated by Django 2.0.4 on 2018-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Crypto', max_length=20)),
                ('symbol', models.CharField(help_text='Enter CRYPTO ticker', max_length=10)),
                ('rank', models.IntegerField()),
                ('price_usd', models.FloatField()),
                ('price_btc', models.FloatField(help_text='Enter Price in BTC value', max_length=18)),
                ('volume_usd_24h', models.FloatField()),
                ('market_cap_usd', models.FloatField()),
                ('available_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('max_supply', models.FloatField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('last_updated', models.FloatField()),
                ('price_eur', models.FloatField()),
                ('volume_eur_24h', models.FloatField()),
                ('market_cap_eur', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
