# Generated by Django 2.0.4 on 2018-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180503_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
