# Generated by Django 2.0.4 on 2018-05-04 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180503_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
