# Generated by Django 2.0.4 on 2018-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180504_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
