# Generated by Django 2.0.4 on 2018-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180430_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='available_supply',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='last_updated',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='market_cap_eur',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='market_cap_usd',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='max_supply',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='percent_change_1h',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='percent_change_24h',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='percent_change_7d',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price_eur',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price_usd',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='total_supply',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='volume_eur_24h',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='volume_usd_24h',
            field=models.FloatField(max_length=20),
        ),
    ]
