# Generated by Django 2.0.4 on 2018-04-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180430_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='price_btc',
            field=models.FloatField(max_length=20),
        ),
    ]
