# Generated by Django 2.0.4 on 2018-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180430_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
