# Generated by Django 2.0.4 on 2018-05-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180501_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(help_text='Enter Crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name_id',
            field=models.CharField(help_text='Enter crypto', max_length=20),
        ),
    ]
