# Generated by Django 2.0.4 on 2018-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180503_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='rank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
