# Generated by Django 2.0.4 on 2018-05-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180504_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='last_updated',
        ),
    ]
