# Generated by Django 2.0.4 on 2018-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_main_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='last_updated',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
