# Generated by Django 2.0.4 on 2018-05-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_main_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
