# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_id', models.CharField(help_text='Enter crypto', max_length=20)),
                ('name', models.CharField(help_text='Enter Crypto', max_length=20)),
                ('symbol', models.CharField(help_text='Enter CRYPTO ticker', max_length=10)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('prices_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prices_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('volume_usd_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('market_usd_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('available_supply', models.CharField(blank=True, max_length=20, null=True)),
                ('total_supply', models.CharField(blank=True, max_length=20, null=True)),
                ('max_supply', models.CharField(blank=True, max_length=20, null=True)),
                ('percent_change_1h', models.CharField(blank=True, max_length=20, null=True)),
                ('percent_change_24h', models.CharField(blank=True, max_length=20, null=True)),
                ('percent_change_7d', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=20, null=True)),
                ('cached', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'main',
            },
        ),
        migrations.AlterUniqueTogether(
            name='main',
            unique_together=set([('name', 'symbol')]),
        ),
    ]
