# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='market_usd_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='volume_usd_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
    ]
